name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this branch based on your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Unzip test.zip
      run: unzip archive_with_site.zip -d deploy-folder  # Adjust the destination folder as needed

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./deploy-folder  # Adjust to the destination folder specified in the unzip step
